name: CI

on:
  schedule:
    - cron: 1 8 * * 5
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: install ansible
        run: |
          sudo apt-add-repository --yes --update ppa:ansible/ansible-2.9
          sudo apt-get upgrade ansible
          
    - uses: actions/checkout@v1
      with:
        path: "./collections/ansible_collections/mafalb/docker"
    - run: pwd
    - run: whoami
    - run: echo $HOME
    - run: ansible-galaxy collection install geerlingguy.php_roles
    - run: ls -R ./collections/ansible_collections/mafalb/docker
    
