name: CI

on:
  schedule:
    - cron: 1 8 * * 5
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        path: '.ansible/collections/ansible_collections/mafalb/docker'
    - run: pwd
    - run: whoami
    - run: echo $HOME
    - run: ls -R $HOME
    
